### ISSUE TITLE
say & think fail

### ISSUE THREAD

**Issue by davewiththenicehat** [TheEternalCitizens/mudlet-integration#15]
Sometimes when attempting to say or think the command is not received server side.
At times it requires repeating three times to get the command to be received.
Possible it is the ac . commands being sent by room checks, but combat works without any issues.
I did not have any troubles sending attack commands.

**Comment by johnnymo87** [comment]
I've heard it said that the server refuses to process more than one message a connection a second. Could these automatic `ac .` messages be blocking regular user input?

**Comment by davewiththenicehat** [comment]
Unfortunately I think you are right.
Even if it were not for this issue. Breaking the hiding skills system with automated room checks is unacceptable.

All I can see as options are:
Require a command or mouse click to refresh the Room Characters list.
Than possibly move it to an option the user can enable.

All current players will want it, even needing to manually run it. They love that level of management.
So burring it in options may push current players to think this new client doesn't really add anything.

New players may be put off by it not auto-refreshing as it does in other games.

Maybe what we could do is make it default in the initial release. Because only existing players will use it. Than in later release move it to optional?

I may be over thinking it. I do that sometimes.

**Comment by davewiththenicehat** [comment]
Resolved with https://github.com/TheEternalCitizens/mudlet-integration/pull/36
