### ISSUE TITLE
Proposed UI/UI elements

### ISSUE THREAD

**Issue by tscheer86** [TheEternalCitizens/mudlet-integration#70]
<img width="563" alt="UI" src="https://user-images.githubusercontent.com/50849125/70935232-b6b1f100-200d-11ea-94cd-2286e8d5635c.PNG">

Proposed UI Element Additions:

- Combat Statistic Tracker
Tracks Hits, Misses, Crit % and Fumble %.
- Inventory
Tracks last known state of Inventory command. Can also include last known state of wealth, and weight from SST.
- Skills/SSK
Tracks last known Skills list (Might be too bloated) and ssk (with +x.xx sp tracker from last known state.)

Rearranged UI elements:
- Condense existing UI elements into an "Orchil" style pane on right side.
- Create third "Middleright" guiFrame
- Sandwich Compass and status bars side by side above TEC map.
- Sandwich Macros between Room Checker and Compass/bars.

**Comment by davewiththenicehat** [comment]
Implemented with commit https://github.com/TheEternalCitizens/mudlet-integration/commit/0e757dfab00ad5ed80ec651395f3bde6d8299054
