### ISSUE TITLE
Compass UI Improvements

### ISSUE THREAD

**Issue by tscheer86** [TheEternalCitizens/mudlet-integration#71]
- [ ] Obtain/create sleeker compass images
- [ ] Replace compass images with a sleeker version
- [ ] Test
- [ ] Implement

**Comment by davewiththenicehat** [comment]
![image](https://user-images.githubusercontent.com/54369722/73074825-82d9af00-3e88-11ea-86b4-f0be03f10d90.png)
Image for format reference.

**Comment by davewiththenicehat** [comment]
Implemented with commit https://github.com/TheEternalCitizens/mudlet-integration/commit/839aa28e7038ce9bfd6f779a2df93596373031a8
