### ISSUE TITLE
Player Request: Phoenix Guard Auto Accept

### ISSUE THREAD

**Issue by tscheer86** [TheEternalCitizens/mudlet-integration#83]
Create feature to auto-accept Phoenix Guard requests to search your persons.

**Comment by tscheer86** [comment]
### **Aliases:**
- [x] Create alias to toggle feature on
- [x] Create alias to toggle feature off
- [x] Create alias to display current feature status
- [x] Create alias to display command list and disclaimers. 
### **Triggers**
- [x] Create trigger for citizens
- [x] Create trigger for foreigners
- [x] Create trigger for patricians
- [x] Create trigger for officials
### **Testing**
- [x] Verify aliases work
- [x] Verify triggers work
- [ ] Verify triggers work with followers

**Comment by davewiththenicehat** [comment]
Going through old issues closing ones out that I can.

This feature will be available with the 0.1.55 release. It is going to be one of the premade interrupts that can be imported with the import button.

Within the week I will upload the automation to auto yes to contraban searched.
With .1.55 and forward automation requests like this can be completed on the user end with two button clicks. One to download new automations and interrupts and a second to import the new automation or interrupt.
This feature is still in fresh beta, but I've already tested it as working.
